# ── Themes ────────────────────────────────────────────────────────────────────
THEMES = {
    "dark": {
        "bg":          "#1e1e2e",
        "surface":     "#313244",
        "output_bg":   "#181825",
        "fg":          "#cdd6f4",
        "fg_muted":    "#6c7086",
        "accent":      "#89b4fa",
        "accent_fg":   "#1e1e2e",
        "muted_bg":    "#45475a",
        "muted_fg":    "#cdd6f4",
        "success":     "#a6e3a1",
        "warning":     "#f9e2af",
        "info":        "#89dceb",
        "danger":      "#f38ba8",
        "insert":      "#cdd6f4",
        "tag_header":  "#89dceb",
        "tag_phys":    "#f9e2af",
        "tag_logical": "#a6e3a1",
        "tag_meta":    "#585b70",
        "tag_table":   "#89b4fa",   # inline: table replacements
        "tag_column":  "#a6e3a1",   # inline: column replacements
        "tag_ambig":   "#f9e2af",   # inline: ambiguous replacements
        "tag_input_hi":"#89dceb",   # input highlight for known tokens
        "tag_search":  "#f38ba8",
        "placeholder": "#585b70",
    },
    "light": {
        "bg":          "#eff1f5",
        "surface":     "#dce0e8",
        "output_bg":   "#e6e9ef",
        "fg":          "#4c4f69",
        "fg_muted":    "#9ca0b0",
        "accent":      "#1e66f5",
        "accent_fg":   "#ffffff",
        "muted_bg":    "#bcc0cc",
        "muted_fg":    "#4c4f69",
        "success":     "#40a02b",
        "warning":     "#df8e1d",
        "info":        "#04a5e5",
        "danger":      "#d20f39",
        "insert":      "#4c4f69",
        "tag_header":  "#04a5e5",
        "tag_phys":    "#df8e1d",
        "tag_logical": "#40a02b",
        "tag_meta":    "#9ca0b0",
        "tag_table":   "#1e66f5",
        "tag_column":  "#40a02b",
        "tag_ambig":   "#df8e1d",
        "tag_input_hi":"#04a5e5",
        "tag_search":  "#d20f39",
        "placeholder": "#acb0be",
    },
}
